### ISSUE TITLE
why i can not add prefab/Fog to my scenes

### ISSUE THREAD

**Issue by GITHUB243884919** [kitepro/FogOfWar#1]
could you upload all project. i can not add prefab/Fog to my scenes
Tow warnings are  follow:
1. Unable to instantiate prefab. Prefab may be broken.
UnityEditorInternal.InternalEditorUtility:HierarchyWindowDrag(HierarchyProperty, Boolean, HierarchyDropMode)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

2. Shader warning in 'TheFallenRealm/Fog/Blur': comma expression used where a vector constructor may have been intended at line 79 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by nishadtardalkar** [comment]
Hey sorry for (too) late response.
Are you by any chance using any SRP?

HDRP or LWRP dont support Projectors instead they have Decals.
So the project needs some modification.

I've uploaded a unitypackage that contains scene setup for both Normal and HDRP Project.
To test HDRP just add the asset file from Settings folder in the package to Project Settings > Graphics > RenderPipeline slot.
