### ISSUE TITLE
[Feature Request] Always visible crossed path

### ISSUE THREAD

**Issue by keyserjaya** [kitepro/FogOfWar#2]
Hello, i've tried this and it was amazing!

But i want to make the crossed path to be always visible just like Starcraft
https://www.youtube.com/watch?v=pQMEvi0OZ_c
on 03:24

I hope u will add that feature ^_^
or do you have any clues how to do that? 

Thank you :)

**Comment by nishadtardalkar** [comment]
Ok I'll try.
Thats an easy one actually. If you open the cookie shader you'll see I have returned 0.05 for fog.
There you have to return color of previous frame render texture. That would be it.
Try it, but I'll commit the changes as well.

**Comment by keyserjaya** [comment]
OMG bro, where did you learn to make this? 
Do you have patreon or youtube channel? ^_^

Thank you so much, u're a life saver!

**Comment by nishadtardalkar** [comment]
I dont have patreon, but I do have a Youtube channel.
I use it just to post the plugins and some random stuff.
You can check it out :
https://www.youtube.com/channel/UCh1VbK-b3wooBKxsOkHVegQ
