### ISSUE TITLE
Some Minor Issues

### ISSUE THREAD

**Issue by ColdFlameStudios** [kitepro/FogOfWar#3]
A few issues that should be relatively simple to solve. 

The Unitypackage and the files themselves seem to be somewhat mismatched, I tried to solve this by importing the unity package after the folders and ignoring the scripts and shaders. The Unitypackage has some items the folders do not, but the folders are newer.

Fog.cs seems to have some minor errors in it. I had to change m_Material and m_Size to material and size respectively. This may have been in error on my part or I may be missing a Unity package? Shown below.
![image](https://user-images.githubusercontent.com/23323742/65340260-d915a900-db9b-11e9-9c90-aa8ea926feab.png)

Using the absolute most basic prefabs with the minor version changes as explained above, everything seems to have broken. These are images of the errors in the example scenes.
![image](https://user-images.githubusercontent.com/23323742/65339972-30674980-db9b-11e9-970c-a4ed54bb3b9b.png)
![image](https://user-images.githubusercontent.com/23323742/65340046-5b519d80-db9b-11e9-8d0a-3f4bb1fe204f.png)

And a completely different issue exists in my own scene. The fog is removed across the Z-axis rather than in a circle around the object.
![image](https://user-images.githubusercontent.com/23323742/65340119-8a680f00-db9b-11e9-8bf6-38245a8b6d6a.png)

This is an incredible effect, I hope you continue to improve this.

**Comment by nishadtardalkar** [comment]
Plugin is updated only to support stable releases of unity.
I'll update these when these changes are permanent. 
For decals m_material is the variable name for previous versions.
And for the Z axis problem, you just have to rotate the projector in the correct direction.
