### ISSUE TITLE
[FEATURE REQUEST] LWRP/URP Support

### ISSUE THREAD

**Issue by keyserjaya** [kitepro/FogOfWar#4]
This plugins might help:
https://nyahoon.com/products/fast-shadow-receiver/use-projectors-in-lwrp-projects
https://nyahoon.com/products/projector-for-lwrp

i will try my best to implement this too :' D

Any clue to to implement this will be very appreciated ^_^

**Comment by keyserjaya** [comment]
I did it, i will close this after contribute ^^

**Comment by mollsju** [comment]
@keyserjaya Care to share how you made it work? Any PR incoming?

**Comment by NikitaSavik** [comment]
Bumping this 👍

**Comment by keyserjaya** [comment]
Sorry guys, too busy last year.
i will try this weekend :'

**Comment by keyserjaya** [comment]
Here u go guys.
https://github.com/keyserjaya/FogOfWar/tree/URP

**Comment by keyserjaya** [comment]
> @keyserjaya Care to share how you made it work? Any PR incoming?

I really don't remember the details :'
Here's how:
1. Download projector for LWRP here: https://nyahoon.com/products/projector-for-lwrp
2. Follow the instruction of "Projector for LWRP"
2. Upgrade shaders to support URP
3. Don't forget to include this on your shader: Assets/ProjectorForLWRP-master-universalrp/Shaders/P4LWRP.cginc
